### ISSUE TITLE
Comparison needs to be its own rule

### ISSUE THREAD

**Issue by roypearce** [shuckster/eslint-plugin-big-number-rules#6]
I see the todo about moving comparisons into its own rule in code. It's a shame it wasn't done earlier because it makes this plugin much less useful to everyone, and this plugin has a lot of great potential, and clearly has had a lot of work put into it. I don't see any activity on the other issues here, so I'm going to assume this project is abandoned.

**Comment by shuckster** [comment]
Hey Roy, thanks for your interest and feedback in the project. It's not abandoned, but certainly between work and family it's sometimes tough to find time for improvements. PRs welcome. :)

As for why I didn't do this earlier, there are a couple reasons for that:

1. An aggressive "catch all" default behaviour actually suits my own use-case very well. I accept that others may prefer a more granular approach though, and I've noticed someone has forked the project to this effect
2. If I break-out comparison from arithmetic I want to ensure that the solution is still reasonably performant. I'm aware there's a lot of code here already, so I worry about large codebases, including the ones I work on

I will try and find time in the next month to address this issue. It's a busy time for me at the moment (isn't everyone busy these days?) but I'll try and get around to it.

Thanks again.

**Comment by roypearce** [comment]
Thanks for responding, and thanks for making this :) I'm glad to hear that you're still interested in maintaining and open to PR's. I wouldn't worry about the size of the codebase for a linting utility since it's not getting deployed with anybody's production code. I don't think breaking these into new rules is going to affect much either way since these things are already being checked.

**Comment by shuckster** [comment]
As of `v1.10.0`, bitwise + comparison rules are now separate from arithmetic rules:

```json
// .eslintrc
{
  "plugins": ["big-number-rules"],
  "rules": {
    "big-number-rules/arithmetic": "warn",
    "big-number-rules/bitwise": "warn",
    "big-number-rules/comparison": "warn"
  }
}
```

These rules are also part of `big-number-rules/recommended`:

```json
// .eslintrc
{
  "plugins": ["big-number-rules"],
  "extends": ["plugin:big-number-rules/recommended"]
}
```

Thank you for the prompt to address this.

**Comment by roypearce** [comment]
This made my day, I wasn't expecting this! Thank you. I'll see if I can contribute back in the future.

**Comment by shuckster** [comment]
Update: Version 2.0.0 of the plugin [will now suggest](https://github.com/shuckster/eslint-plugin-big-number-rules#but-i-use--for-string-concatenation) an `Object.is` alternative for the equality operators `===` and `==`. Also, `String#concat()` and `Template String` replacements are also now offered for `+` related rules.
